networks:
  php_pro:
    driver: bridge

volumes:
  database_volume:
    driver: local

services:
  app:
    build:
      context: php
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    command: /usr/bin/sh -c "/usr/bin/chmod +x /var/www/html/migration.sh && ln -s /var/www/html/migration.sh /usr/local/bin/migration && apache2-foreground"
    networks:
      - php_pro

  database:
    image: 'mysql:8'
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - 'database_volume:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    networks:
      - php_pro
